apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: shulker
  namespace: shulker-system
spec:
  chart:
    spec:
      chart: kube/helm
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: shulker
  interval: 60m
  install:
    remediation:
      retries: 3
  test:
    enable: true
  values:
    operator:
      metrics:
        enable: false