---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: shulker
  namespace: shulker-system
spec:
  ignore: |-
    # exclude all
    /*
    # include charts directory only
    !/kube/helm
  interval: 5m0s
  ref:
    tag: v0.4.0
  url: https://github.com/jeremylvln/Shulker
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: shulker
  namespace: shulker-system
spec:
  chart:
    spec:
      chart: kube/helm
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: shulker
  interval: 5m0s
