---
apiVersion: v1
kind: Namespace
metadata:
  name: agnoes-system
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: agnoes-system
  namespace: agnoes-system
spec:
  interval: 24h
  url: https://agones.dev/chart/stable
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: agnoes-system
  namespace: agnoes-system
spec:
  interval: 30m
  chart:
    spec:
      chart: agnoes-system
      sourceRef:
        kind: HelmRepository
        name: agnoes-system
        namespace: agnoes-system
      interval: 12h
  values:
    agones:
      allocator:
        install: true
        service:
          serviceType: ClusterIP
      ping:
        http:
          serviceType: ClusterIP
        udp:
          serviceType: ClusterIP
    # gameservers:
    #   namespaces:
    #     - shulker-system