---
apiVersion: v1
kind: Namespace
metadata:
  name: agones
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: agones
  namespace: agones
spec:
  interval: 24h
  url: https://agones.dev/chart/stable
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: agones
  namespace: agones
spec:
  chart:
    spec:
      chart: agones
      sourceRef:
        kind: HelmRepository
        name: agones
        namespace: agones
      interval: 12h
  interval: 30m
  values:
    agones:
      allocator:
        install: true
        service:
          serviceType: ClusterIP
      ping:
        http:
          serviceType: ClusterIP
        udp:
          serviceType: ClusterIP
    gameservers:
      namespaces:
        - shulker-system
