apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: shulker
  namespace: shulker-system
spec:
  test:
    enable: false
  values:
    operator:
      metrics:
        enabled: true